-- Insert Sample Patient Reports
-- Run this after creating tables and sample data

INSERT INTO patient_reports (patient_id, report_type, content, created_at) VALUES
(1, 'Medical Assessment', 'Patient presents with symptoms of hypertension. Blood pressure readings consistently above 140/90. Recommended lifestyle changes including reduced sodium intake and regular exercise. Follow-up appointment scheduled in 2 weeks.', NOW()),
(2, 'Lab Results', 'Complete Blood Count (CBC) Results:\n- Hemoglobin: 13.5 g/dL (Normal)\n- White Blood Cell Count: 7.2 K/uL (Normal)\n- Platelet Count: 250 K/uL (Normal)\nChemistry Panel:\n- Glucose: 95 mg/dL (Normal)\n- Creatinine: 1.0 mg/dL (Normal)\nAll values within normal limits. No abnormalities detected.', NOW()),
(3, 'Diagnosis', 'Patient diagnosed with Type 2 Diabetes Mellitus. Fasting blood glucose level 156 mg/dL. HbA1c 7.8%. Patient counseled on diet, exercise, and medication management. Prescribed Metformin 500mg twice daily. Referred to diabetes educator for comprehensive patient education.', NOW()),
(4, 'Treatment Plan', 'Comprehensive treatment plan for Managing Chronic Migraines:\n1. Preventive Therapy: Start Propranolol 40mg daily\n2. Acute Treatment: Sumatriptan 50mg as needed\n3. Lifestyle Modifications: Regular sleep, stress management, hydration\n4. Dietary Changes: Avoid known triggers (caffeine, MSG, aged cheeses)\n5. Follow-up: Monthly review with neurologist\nExpected improvement within 4-6 weeks.', NOW()),
(5, 'Discharge Summary', 'Patient Name: Michael Davis\nAdmission Date: 2026-04-10\nDischarge Date: 2026-04-15\nDiagnosis: Acute Appendicitis\nProcedure: Laparoscopic Appendectomy\nPost-operative Course: Uneventful. Patient tolerating oral diet well.\nDischarge Instructions: Rest, avoid strenuous activities for 4 weeks, pain management with acetaminophen. Follow-up with surgeon in 1 week.', NOW()),
(6, 'Prescription Report', 'Current Active Prescriptions:\n1. Lisinopril 10mg - Daily (Hypertension)\n2. Atorvastatin 40mg - Daily (Cholesterol)\n3. Metformin 500mg - Twice Daily (Diabetes)\n4. Vitamin D3 2000IU - Daily (Supplementation)\nPatient advised on medication adherence and reported no adverse effects. All prescriptions refilled.', NOW()),
(7, 'Medical Assessment', 'Annual Physical Examination:\nVital Signs: BP 120/80, HR 72, RR 16, Temp 98.6F\nPhysical Exam: Normal findings on cardiovascular, respiratory, and abdominal examination.\nLabs: All routine screening tests normal.\nAssessment: Healthy 32-year-old female with no acute concerns. Preventive health measures discussed including immunizations and cancer screenings. Continue current healthy lifestyle.', NOW()),
(8, 'Lab Results', 'Thyroid Function Test Results:\n- TSH: 2.1 mIU/L (Normal Range: 0.4-4.0)\n- Free T4: 1.2 ng/dL (Normal Range: 0.8-1.8)\n- Free T3: 3.1 pg/mL (Normal Range: 2.3-4.2)\nInterpretation: Normal thyroid function. No evidence of hypothyroidism or hyperthyroidism. Patient can continue current management.', NOW()),
(9, 'Diagnosis', 'Patient diagnosed with Anxiety Disorder, Generalized Type. Symptoms include persistent worry, restlessness, and sleep disturbance for past 3 months. Psychosocial stressors identified and addressed. Started on Sertraline 50mg daily. Referred for cognitive behavioral therapy. Follow-up in 4 weeks to assess response to treatment.', NOW()),
(10, 'Treatment Plan', 'Orthopedic Treatment Plan - Knee Osteoarthritis:\n1. Physical Therapy: 2x/week for 6 weeks focusing on strengthening and flexibility\n2. Pain Management: Ibuprofen 400mg as needed, Topical NSAIDs\n3. Lifestyle: Weight management, activity modification, proper footwear\n4. Injections: Consider hyaluronic acid injections if conservative management ineffective\n5. Surgery: Evaluate for total knee replacement if conservative measures fail after 6 months\n6. Follow-up: Every 4 weeks initially, then monthly.', NOW());
